version: "3.5"
services:
  referenten:
    volumes:
      - "./app:/var/www"
      - "./update.d:/update.d"
      - "${VOLUMES_DIR}/profilbilder:/var/www/html/profilbilder"

  referenten-adminer:
    image: adminer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.referenten-adminer.entrypoints=websecure
      - traefik.http.routers.referenten-adminer.rule=Host(`referenten-adminer.${DOMAINNAME}`)
      - traefik.http.routers.referenten-adminer.tls=true
      - traefik.http.routers.referenten-adminer.tls.certresolver=myresolver
      - traefik.http.routers.referenten-adminer.middlewares=secheader@file
    depends_on:
      - referenten-database
    networks:
      - traefik
      - referenten
