services:
  db:
    image: mariadb
    restart: unless-stopped
    container_name: ${SERVICENAME}-database
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"

  app:
    image: ghcr.io/mind-hochschul-netzwerk/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    volumes:
      - "${VOLUMES_DIR}/profilbilder:/var/www/html/profilbilder"
    environment:
      - DOMAINNAME
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - TOKEN_KEY
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - FROM_ADDRESS
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICENAME}.middlewares=secheader@file
    depends_on:
      - db
    networks:
      - traefik
      - default
      - akademie

  adminer:
    image: adminer
    container_name: ${SERVICENAME}-adminer
    labels:
      - traefik.enable=true
    depends_on:
      - db
    networks:
      - traefik
      - default

networks:
  traefik:
    name: traefik
    external: true
  akademie:
    name: akademie
    external: true
