name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '23 2 * * 1'
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: Mind-Hochschul-Netzwerk/.github/.github/workflows/ci.yaml@main
    with:
      registry: ${{ vars.REGISTRY }}
      image_name: ${{ vars.IMAGE_NAME }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
